### ISSUE TITLE
Recommendations toggle in bottom left Files settings

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/recommendations#108]
**Is your feature request related to a problem? Please describe.**

Discussed in nextcloud/recommendations#100 with @jancborchardt. 

We are currently working on adding the ability for users to disable Recommendations for themselves. The previous plan was to have a separate settings page for Recommendations but  it would be nice to add the setting to the sidebar of the Files app instead. The idea would be for the Files app will check if the Recommendations app is installed, then if installed, give the setting to toggle Recommendations.

If the idea sounds okay, I'll open a pull request.

**Comment by skjnldsv** [comment]
Moved, this is not a server issue :)

**Comment by gary-kim** [comment]
> Moved, this is not a server issue :)

It isn't a server issue though will require a server change. Should we open a new issue for adding an api for injecting settings?

**Comment by skjnldsv** [comment]
@gary-kim yes definitely! :)
Sorry I forgot about this! Thanks for the reminder! you rock! :hugs:
