### ISSUE TITLE
Filter by Mime type

### ISSUE THREAD

**Issue by sunjam** [nextcloud/recommendations#111]
Hi, my casual thought is to filter out Recommendations by mime type.  Example is in filtering out encrypted files such as:

*.gpg - used by many iterations of [Pass](https://www.passwordstore.org/)
*.kdb and *.kdbx used by [Keeweb app](https://apps.nextcloud.com/apps/keeweb)

This could help with #78 blacklists request, but would work on a general basis as opposed to blacklisting specific folders or individual files as requested in that issue.

**Comment by ChristophWurst** [comment]
Although this sounds like an interesting feature, the number of requests for this are quite low. Currently there a no plans to implement such a feature, hence I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

Thank you :v:
