### ISSUE TITLE
optionally Hide Recommendations in Grid View

### ISSUE THREAD

**Issue by sunjam** [nextcloud/recommendations#113]
Related to #72 I would like to request the user's ability to hide Recommendations when specifically in Grid view of the Files app, without having to fully disable the app.

Thanks for considering!

**Comment by ChristophWurst** [comment]
I think once there is a toggle for #72 we're covering most cases. Anything else is too specific and we can't cover *all* use cases, unfortunately without cluttering the interface with thousands of settings. I hope this makes sense.

**Comment by sunjam** [comment]
That covers whether to display the Recommendations at all, I actually filed that request, but another extremely common one would be to disable Recommendations only when in Grid or File View.  Considering File and Grid views are the only ones available, it would be a useful toggle.  Thank you either way.

**Comment by ChristophWurst** [comment]
Yes, I understand the use case. But IMO a personal setting to show/hide recommendations is good enough. Even if there are just two modes we'd need *Show recommendations in list view* and *show recommendation in grid view*. For most users, however, these settings would not be relevant.

Thanks for the input, though!
