### ISSUE TITLE
missing documentation: what does files:recommendations:recommend do?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/recommendations#220]
I lately found the files:recommendations:recommend command.
What does that do? I think a documentation should be added.
Thanks!

**Comment by ChristophWurst** [comment]
It was merely used for testing but this shows the recommendations a user will get to see on top of their files. We might just remove https://github.com/nextcloud/recommendations/blob/master/lib/Command/GetRecommendations.php.

**Comment by szaimen** [comment]
Okay, thanks 👍
