### ISSUE TITLE
Strings to translate

### ISSUE THREAD

**Issue by JSoko** [nextcloud/recommendations#266]
Please have a look on what's sent to transifex. 
A lot of strings are shown in transifex which are probably not supposed to be translated.
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/recommendations/

**Comment by rakekniven** [comment]
Just added a PR to fix this.

We constantly have issues with strings at Transifex related to packed javascript files from GitHub.
Can we have a general solution for that?

I would really appreciate any work on this.

**Comment by gary-kim** [comment]
Closed by #267
