### ISSUE TITLE
Multiselect table header overlays the recommendations

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/recommendations#29]
* selecting a file in the list shows the multiselect header
* expected: it does not overlay the recommendations
* actual: it does overlay the recommendations

<img width="1339" alt="bildschirmfoto 2019-02-18 um 16 49 55" src="https://user-images.githubusercontent.com/245432/52962322-43176700-339d-11e9-8e1c-faed56dfe47d.png">

cc @ChristophWurst

**Comment by MorrisJobke** [comment]
@ChristophWurst 🏓

**Comment by ChristophWurst** [comment]
What would be the fix? @jancborchardt please have a look

**Comment by jancborchardt** [comment]
Considering the Recommendations list can have variable height (up to 3 rows) we might need to put the multiselect bar in a lower container to position it relatively?

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/server/pull/15164
