### ISSUE TITLE
Clicking a preview should open the viewer/edit, if possible

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/recommendations#33]
The behavior is different from the filelist itself. When you click on an image or text file, it should open the viewer or the texteditor – but currently it just opens the sidebar.

**Comment by MorrisJobke** [comment]
@ChristophWurst 🏓

**Comment by ChristophWurst** [comment]
I would argue navigation is better than opening directly. At least for the user cases I recently had this is what I wanted. And you can always just open the file once navigated -> wontfix.

**Comment by ChristophWurst** [comment]
I have a better idea: clicking the thumbnail should open the image viewer or editor.

**Comment by jancborchardt** [comment]
The behavior should be the same no matter if you tap on the thumbnail or on the filename, otherwise it will be confusing.

> I would argue navigation is better than opening directly. At least for the user cases I recently had this is what I wanted. And you can always just open the file once navigated -> wontfix.

Yep, that seems fine. Also then it's consistent no matter if it's file or folder.
