### ISSUE TITLE
Not updating on objectstorage.

### ISSUE THREAD

**Issue by hahagu** [nextcloud/recommendations#337]
Possibly a nextcloud bug, also possibly related to
https://github.com/nextcloud/photos/issues/522

The recommendations feed does not update when the primary storage is set to objectstorage, such as the amazon S3.

**Comment by ChristophWurst** [comment]
Recommendations shows whatever is known to Nextcloud Files. If there is a limitation there it will spill over to this app. We just use the files API here. Nothing much we can do about this.

**Comment by hahagu** [comment]
This looks like a bug within the Files API itself, and not this app.
I have issued a bug report on the server repository. 

https://github.com/nextcloud/server/issues/24417

P.S. It would be helpful if you could go and support or suggest solutions on the above issue.
Thanks!

**Comment by ChristophWurst** [comment]
> P.S. It would be helpful if you could go and support or suggest solutions on the above issue.

This is a community project.
