### ISSUE TITLE
Do not recommend filechanges in hidden folders

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/recommendations#456]
at least if the user has deactivate show hidden files

![image](https://user-images.githubusercontent.com/24530680/141930830-22ca62e0-176f-4b08-90e2-ea3a09e8f658.png)

**Comment by ChristophWurst** [comment]
That would require `\OCP\Files\Folder::getRecent` to have some filter arguments

**Comment by ChristophWurst** [comment]
This can be closed as duplicate of https://github.com/nextcloud/recommendations/issues/71
