### ISSUE TITLE
Recommendations list always empty when queried through Dashboard API

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/recommendations#563]
Both Nextcloud and recommendations at `stable25`.

Dashboard widget in the UI:

<details>

![image](https://user-images.githubusercontent.com/8677743/197201757-549f2e02-4d3a-4cb7-b12d-ac9c4f0e9e29.png)

</details>

Through the Dashboard API:

```bash
curl -u test:test http://nextcloud.address/ocs/v2.php/apps/dashboard/api/v1/widget-items\?items\[\]\=recommendations  \
     -H "Accept:application/json"
#
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"spreed":[]}}}
```

Not sure what that `spreed` is doing there, but that is the response I get. Initially found via https://github.com/nextcloud/android/issues/10866

**Comment by AlvaroBrey** [comment]
Same result with alternative API call:

```bash
curl -u test:test http://nextcloud.address/ocs/v2.php/apps/dashboard/api/v1/widget-items \
    -H "Content-Type:application/json" \
    -H "Accept:application/json" \
    -X GET \
    -d '{"sinceIds":{"recommendations":"2022-10-20T15:01:10Z"}}'
#
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"spreed":[]}}}%    
```

**Comment by ChristophWurst** [comment]
Could this be related to https://github.com/nextcloud/server/pull/33788? Are the file changes older than 2w?

**Comment by AlvaroBrey** [comment]
> Could this be related to [nextcloud/server#33788](https://github.com/nextcloud/server/pull/33788)? Are the file changes older than 2w?

No, they are from 2 days ago

**Comment by ChristophWurst** [comment]
What are you testing with? Server master or 25? https://github.com/nextcloud/recommendations/pull/543#issuecomment-1254834444 :zipper_mouth_face:

**Comment by AlvaroBrey** [comment]
> What are you testing with? Server master or 25? [#543 (comment)](https://github.com/nextcloud/recommendations/pull/543#issuecomment-1254834444) zipper_mouth_face

25. That would explain it 😅 let me test master real quick

**Comment by AlvaroBrey** [comment]
Can confirm it does work properly on master

**Comment by ChristophWurst** [comment]
Fixed with https://github.com/nextcloud/recommendations/pull/564
