### ISSUE TITLE
Design regressions of "Recommended files" widget

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/recommendations#660]
There are some regressions to the recommended Files widget as seen below:
- [x] Filetypes without preview are shown as if they are avatar placeholders, not with their proper mimetype icon
- [x] Folders are put in a circle, not just shown as icon
- [x] Similar for previews, they are circled, but should be a square with rounded corners like in the Files app
- [x] File names are aligned to the top, but should be vertically centered with the filetype icon / preview as before
- [x] File extensions are shown same color as filename, but should be color-text-maxcontrast as we do in Files

Intended | Current Nextcloud
-|-
![image](https://github.com/nextcloud/recommendations/assets/925062/775f8fe5-0322-4932-b334-e94b09edfee3)|![image](https://github.com/nextcloud/recommendations/assets/925062/c83d888f-ddeb-4ec9-b93c-041f7bb31336)

**Comment by jancborchardt** [comment]
@szaimen @marcoambrosini could one of you pick this up to fix this, maybe even for 29? It’s a regression which makes the Dashboard look a bit unpolished.

**Comment by susnux** [comment]
@jancborchardt the dashboard widget looks exactly like all others - if you prefer the less rounded one then we need to change it also for all others (e.g. the "statuses" dashboard).

**Comment by susnux** [comment]
Like the general dashboard widget styles are that rounded - same as the login box.
![Screenshot 2024-03-09 at 15-47-19 Nextcloud](https://github.com/nextcloud/recommendations/assets/1855448/bedb4fa1-3f46-4366-a961-ea9ca8c5c406)
![Screenshot 2024-03-09 at 15-47-04 Dashboard - Nextcloud](https://github.com/nextcloud/recommendations/assets/1855448/5b52fd97-b4e8-4e3b-b8ae-2ad2d37772ec)

Unrelated but we should probably either use the drop shadow for all of these components or for none for consistency (there is shadow for the login box but not for dashboard widgets), no?

**Comment by jancborchardt** [comment]
> @jancborchardt the dashboard widget looks exactly like all others - if you prefer the less rounded one then we need to change it also for all others (e.g. the "statuses" dashboard).

@susnux sorry the screenshot is a bit confusing – I am not talking about the bigger border-radius of the outside container, that is of course fine. :) I mean that the filetype icons themselves are in a rounded container, being cut off.

**Comment by susnux** [comment]
Ah yes I see, the avatar component should probably not used here, it makes not much sense.

**Comment by emoral435** [comment]
This seems interesting. I have time right now to pick this up, so will be working on this 👍

**Comment by emoral435** [comment]
Really weird finding --- on my mac, the recommendations widget seems to be pulling directly from the recommendations app itself:

<img width="380" alt="image" src="https://github.com/nextcloud/recommendations/assets/110193237/25803c6c-7c13-4edc-a99e-f34a6f3d0535">

However, on my windows, it seems like the dashboard widget is using our default NcWidget component, and other default dashboard components. Will try to debug this, but it is a bit weird 😕

**Comment by jancborchardt** [comment]
This was all fixed by now.
