### ISSUE TITLE
Doesn't work on Nc16 RC2

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/recommendations#69]
PHP 7.3.4, Apache, sqlite.

Javascript console in Chrome:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:18)
    at XMLHttpRequest.p.(/nextcloud-15/index.php/apps/files/anonymous function) (http://127.0.0.1/nextcloud-15/apps/recommendations/js/main.js?v=6e1824ee-0:7:67341)
```

**Comment by jospoortvliet** [comment]
Ok forget it, seems I built it wrong or something... Getting a fresh install fixed it...

**Comment by jospoortvliet** [comment]
Same on my private instance updated to RC2... So there's some problem.

**Comment by lars-becker** [comment]
I have the same problem on a long running instance which was upgraded since OwnCloud 6. On a recent installation the recommendations app runs without any problems. Wasn't able to find out whats the difference.

**Comment by lars-becker** [comment]
I looked into it and found some strange log messages.It seems like the recommendation app looks for a shared folder on a location where there's no shared file (Shared/FF). But the folder I shared lies in another path and was never located in this location.

I guess there might be some kind of problem with recursions?   `/Shared/` is the configured `share_folder`. I shared the FF folder with a group that I am member of. The share does not appear to me in "/Shared" but only in the location I shared it from. When I delete the FF folder the recommendations show up. When I restore the folder the file not found messages return.

Here is the relevant part of the log file:
[...]
`"app":"index","method":"GET","url":"\/index.php\/apps\/recommendations\/api\/recommendations","message":{"Exception":"OCP\\Files\\NotFoundException","Message":"\/lars\/files\/Shared\/FF","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Folder.php","line":134,"function":"get","class":"OC\\Files\\Node\\Root","type":"->","args":["\/lars\/files\/Shared\/FF"]},{"file":"\/var\/www\/nextcloud\/apps\/recommendations\/lib\/Service\/RecentlySharedFilesSource.php","line":122,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->","args":["\/Shared\/FF"]},{"function":"OCA\\Recommendations\\Service\\{closure}","class":"OCA\\Recommendations\\Service\\RecentlySharedFilesSource","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/apps\/recommendations\/lib\/Service\/RecentlySharedFilesSource.php","line":127,"function":"array_map","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***",{"__class__":"OC\\Share20\\Share"},{"__class__":"OC\\Share20\\Share"},{"__class__":"OC\\Share20\\Share"},{"__class__":"OC\\Share20\\Share"},{"__class__":"OC\\Share20\\Share"}]]},{"file":"\/var\/www\/nextcloud\/apps\/recommendations\/lib\/Service\/RecommendationService.php","line":91,"function":"getMostRecentRecommendation","class":"OCA\\Recommendations\\Service\\RecentlySharedFilesSource","type":"->","args":[{"__class__":"OC\\User\\User"},6]},{"function":"OCA\\Recommendations\\Service\\{closure}","class":"OCA\\Recommendations\\Service\\RecommendationService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/apps\/recommendations\/lib\/Service\/RecommendationService.php","line":92,"function":"array_reduce","args":[[{"__class__":"OCA\\Recommendations\\Service\\RecentlyCommentedFilesSource"},{"__class__":"OCA\\Recommendations\\Service\\RecentlyEditedFilesSource"},"*** sensitive parameter replaced ***"],{"__class__":"Closure"},[]]},{"file":"\/var\/www\/nextcloud\/apps\/recommendations\/lib\/Controller\/RecommendationController.php","line":63,"function":"getRecommendations","class":"OCA\\Recommendations\\Service\\RecommendationService","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"index","class":"OCA\\Recommendations\\Controller\\RecommendationController","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Recommendations\\Controller\\RecommendationController"},"index"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Recommendations\\Controller\\RecommendationController"},"index"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Recommendations\\Controller\\RecommendationController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"recommendations.recommendation.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"recommendations.recommendation.index"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"recommendations.recommendation.index"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/recommendations\/api\/recommendations"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Root.php","Line":202,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.8"}`

**Comment by jospoortvliet** [comment]
I've got this in my logs:
```
[index] Error: OCP\Files\NotFoundException: Node for share not found, fileid: 3207194 at <<closure>>

 0. /srv/www/htdocs/nextcloud/apps/recommendations/lib/Service/RecentlySharedFilesSource.php line 123
    OC\Share20\Share->getNode()
 1. <<closure>>
    OCA\Recommendations\Service\RecentlySharedFilesSource->OCA\Recommendations\Service\{closure}("*** sensitive parameters replaced ***")
 2. /srv/www/htdocs/nextcloud/apps/recommendations/lib/Service/RecentlySharedFilesSource.php line 127
    undefinedundefinedarray_map(Closure {}, [OC\Share20\Shar ... "])
 3. /srv/www/htdocs/nextcloud/apps/recommendations/lib/Service/RecommendationService.php line 91
    OCA\Recommendations\Service\RecentlySharedFilesSource->getMostRecentRecommendation(OC\User\User {}, 6)
 4. <<closure>>
    OCA\Recommendations\Service\RecommendationService->OCA\Recommendations\Service\{closure}("*** sensitive parameters replaced ***")
 5. /srv/www/htdocs/nextcloud/apps/recommendations/lib/Service/RecommendationService.php line 92
    undefinedundefinedarray_reduce([OCA\Recommendat ... "], Closure {}, [])
 6. /srv/www/htdocs/nextcloud/apps/recommendations/lib/Controller/RecommendationController.php line 63
    OCA\Recommendations\Service\RecommendationService->getRecommendations(OC\User\User {})
 7. /srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Recommendations\Controller\RecommendationController->index()
 8. /srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Recommendati ... {}, "index")
 9. /srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Recommendati ... {}, "index")
10. /srv/www/htdocs/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Recommenda ... r", "index", OC\AppFramework\ ... {}, {_route: "recomm ... "})
11. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "recomm ... "})
12. /srv/www/htdocs/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "recomm ... "})
13. /srv/www/htdocs/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/apps/recommend ... s")
14. /srv/www/htdocs/nextcloud/index.php line 42
    OC::handleRequest()

GET /apps/recommendations/api/recommendations
from 192.168.1.167 by jospoortvliet at 2019-04-23T07:17:25+00:00
```
