### ISSUE TITLE
clicking on folder in workspaces does not open the folder

### ISSUE THREAD

**Issue by szaimen** [nextcloud/recommendations#714]
just tested on nc29.0.0b1:
clicking this folder in the header does not open it:
![image](https://github.com/nextcloud/recommendations/assets/42591237/4e517800-f0e3-48ef-b325-18364918a18f)

**Comment by juliushaertl** [comment]
@jancborchardt Might be something more in scope of the files team

**Comment by jancborchardt** [comment]
FYI @sorbaugh
