### ISSUE TITLE
Show / Hide Recommendations View

### ISSUE THREAD

**Issue by sunjam** [nextcloud/recommendations#72]
I'd like the ability to show / hide recommendations.

Example, when I switch to grid view I find the Recommendations visually distracting.

- [ ] Requires https://github.com/nextcloud/server/issues/16602

**Comment by gary-kim** [comment]
I'll see if I can add a user settings page where the recommendations can be disabled per user.

**Comment by sunjam** [comment]
> I'll see if I can add a user settings page where the recommendations can be disabled per user.

I believe User Settings are located on the bottom left of the Files app.  Screenshot attached:

![1560867088](https://user-images.githubusercontent.com/1787238/59691867-9b6a4400-9198-11e9-814f-8a5d992544a7.png)

**Comment by gary-kim** [comment]
The issue is that the settings on the bottom left of the Files app is part of the Files app. I don't think it is possible to add another setting there from another app. Please let me know otherwise.

**Comment by ChristophWurst** [comment]
Right, there is no way to inject custom settings (right now).

**Comment by gary-kim** [comment]
Change reverted

**Comment by pm-pm** [comment]
Please note:
**Do not enable such a "silly" app by default without notification of user.**
It made me crazy until I found the solution to the "remove recent files"!

Thanks.

**Comment by ChristophWurst** [comment]
> Do not enable such a "silly" app by default

@pm-pm please be respectful and read our https://nextcloud.com/contribute/code-of-conduct/

**Comment by kesselb** [comment]
The text app found a way how to inject a custom setting without touching the core: https://github.com/nextcloud/text/blob/master/src/files.js

![image](https://user-images.githubusercontent.com/3902676/71207244-b8e2ac80-22a6-11ea-8b4b-7aee82e5b84c.png)

So this probably not longer blocked but a official api is still missing.

**Comment by gary-kim** [comment]
Could just insert it like that I guess. How about we do that for now then get back to dealing with the debt later?

**Comment by ChristophWurst** [comment]
> Could just insert it like that I guess. How about we do that for now then get back to dealing with the debt later?

Good one. This is exactly why we don't have proper APIs for so many things :see_no_evil:

**Comment by kesselb** [comment]
> This is exactly why we don't have proper APIs for so many things

The usual tradeoff between get things done and dooing it right :rofl:
