### ISSUE TITLE
Recommendations panel does not load if any deleted share exists

### ISSUE THREAD

**Issue by danielepercivaldi** [nextcloud/recommendations#80]
To reproduce:

1. accept a share from any other user
2. remove it from your profile. Now you can find it in he "share recycle bin".
3. back to all files view

Expected result: Recommendations panel does loads

Result: Recommendations panel does not load

Environment:
Ubuntu 18.04; NC 16.0.1; Apache 2.4.29; Recommendations 0.4.0

GC Console logs:
main.js?v=07b80c17-37:7 GET https://box.intre.it/apps/recommendations/api/recommendations 500 (Internal Server Error)
(anonymous) @ main.js?v=07b80c17-37:7
e.exports @ main.js?v=07b80c17-37:7
e.exports @ main.js?v=07b80c17-37:14
Promise.then (async)
s.request @ main.js?v=07b80c17-37:14
s.<computed> @ main.js?v=07b80c17-37:14
(anonymous) @ main.js?v=07b80c17-37:7
load @ main.js?v=07b80c17-37:14
show @ main.js?v=07b80c17-37:14
(anonymous) @ main.js?v=07b80c17-37:34
setTimeout (async)
attach @ main.js?v=07b80c17-37:34
attach @ main.js?v=07b80c17-37:120
initialize @ merged-index.js?v=07b80c17-37:5037
FileList @ merged-index.js?v=07b80c17-37:4659
initialize @ merged-index.js?v=07b80c17-37:84
(anonymous) @ merged-index.js?v=07b80c17-37:344
(anonymous) @ main.js?v=07b80c17-37:39
setTimeout (async)
(anonymous) @ main.js?v=07b80c17-37:39
(anonymous) @ main.js?v=07b80c17-37:39
P @ main.js?v=07b80c17-37:39
i @ main.js?v=07b80c17-37:39
(anonymous) @ merged-index.js?v=07b80c17-37:343
u @ main.js?v=07b80c17-37:39
fireWith @ main.js?v=07b80c17-37:39
ready @ main.js?v=07b80c17-37:39
O @ main.js?v=07b80c17-37:39
Error: Request failed with status code 500
    at e.exports (main.js?v=07b80c17-37:7)
    at e.exports (main.js?v=07b80c17-37:14)
    at XMLHttpRequest.p.<computed> (main.js?v=07b80c17-37:7)

**Comment by ChristophWurst** [comment]
Dup of #69, fixed with #79
